apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics: 
    - type: Resource # tipo de metrica baseada nos recursos do app
      resource:
        name: cpu # utilizar recurso cpu como criterio
        target:
          type: Utilization # Baseado na utilizacao dele
          averageUtilization: 50 # ele mantenha um uso medio de 50% de consumo de cpu