apiVersion: v1
kind: Pod
metadata:
  name: bd-pod
  labels:
    app: label-bd
spec:
  containers:  
    - name: bd-pod-container
      image: elvis7t/mysql:1.1    
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
        