apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod
  labels:
    app: lb-pod-1
spec:
  containers:
  - name: primeiro-pod-container
    image: nginx:1.21.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
