apiVersion: v1
kind: Pod
metadata:
  name: segundo-pod
  labels:
    app: lb-pod-2
spec:
  containers:
  - name: segundo-pod-container
    image: nginx:1.21.6
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
