apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
    - name: app2-pod-container
      image: elvis7t/app_curso_online:1.1 
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc-2