apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  # labels:
  #   name: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
    - name: jenkins-container
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /C/xammp/htdocs/pratica_kubernetes/primeiro-volume
        type: Directory
  
