apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pod-app
      name: pod-app
    spec:
      containers:
        - name: app-pod2-container
          image: elvis7t/app_curso_online:1.1 
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-configmap
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/images/
            - name: sessao
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagens-pvc
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc
  selector:
    matchLabels:
      app: pod-app
  serviceName: svc-nodeport-app
